config/routes.rb
ActiveWorkflow::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      put :leave_workflow
      delete :remove_messages
      delete :memory, action: :destroy_memory
    end

    collection do
      get :table
      put :toggle_visibility
      get :type_details
      get :message_descriptions
      post :validate
      post :complete
      delete :undefined, action: :destroy_undefined
    end

    resources :logs, only: [:index] do
      collection do
        delete :clear
      end
    end

    resources :messages, only: [:index, :show, :destroy] do
      member do
        post :reemit
      end
    end

    scope module: :agents do
      resources :dry_runs, only: [:index, :create]
    end
  end

  scope module: :agents do
    resources :dry_runs, only: [:index, :create]
  end

  resources :workflows do
    collection do
      resource :workflow_imports, only: [:new, :create]
    end

    member do
      get :share
      get :export
      put :enable_or_disable_all_agents
      post :reset
    end

    resource :diagram, only: [:show]
  end

  resources :user_credentials, except: :show do
    collection do
      post :import
    end
  end

  resources :jobs, only: [:index, :destroy] do
    member do
      put :run
    end
    collection do
      delete :destroy_failed
      delete :destroy_all
      post :retry_queued
    end
  end

  namespace :admin do
    resources :users, except: :show do
      member do
        put :deactivate
        put :activate
        get :switch_to_user
      end
      collection do
        get :switch_back
      end
    end
  end

  get '/worker_status' => 'worker_status#show'

  match '/users/:user_id/web_requests/:agent_id/:secret' => 'web_requests#handle_request', :as => :web_requests, :via => [:get, :post, :put, :delete]

  devise_for :users,
             controllers: {
               registrations: 'users/registrations'
             },
             sign_out_via: [:post, :delete]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  mount API::V1::Root => '/api'

  get '/about' => 'home#about'
  root to: 'home#index'
end

app/models/message.rb
# Messages are how ActiveWorkflow Agents communicate and log information about the world.  Messages can be emitted and received by
# agents.  They contain a serialized `payload` of arbitrary JSON data, as well as `expires_at` fields.
class Message < ApplicationRecord
  include JSONSerializedField
  include LiquidDroppable

  json_serialize :payload

  belongs_to :user, optional: true
  belongs_to :agent, counter_cache: true

  has_many :agent_logs_as_inbound_message, class_name: 'AgentLog', foreign_key: :inbound_message_id, dependent: :nullify, inverse_of: :inbound_message
  has_many :agent_logs_as_outbound_message, class_name: 'AgentLog', foreign_key: :outbound_message_id, dependent: :nullify, inverse_of: :outbound_message

  scope :recent, lambda { |timespan = 12.hours.ago|
    where('messages.created_at > ?', timespan)
  }

  after_create :update_agent_last_message_at

  scope :expired, lambda {
    where('expires_at IS NOT NULL AND expires_at < ?', Time.now)
  }

  scope :to_expire, -> { expired }

  # Emit this message again, as a new message.
  def reemit!
    agent.create_message payload: payload
  end

  # Look for Messages whose `expires_at` is present and in the past.  Remove those messages and then update affected agents'
  # `messages_counts` cache columns.
  # rubocop:disable Rails/SkipsModelValidations
  def self.cleanup_expired!
    transaction do
      affected_agents = Message.expired.group('agent_id').pluck(:agent_id)
      Message.to_expire.delete_all
      Agent.where(id: affected_agents).update_all 'messages_count = (select count(*) from messages where agent_id = agents.id)'
    end
  end
  # rubocop:enable Rails/SkipsModelValidations

  protected

  # rubocop:disable Rails/SkipsModelValidations
  def update_agent_last_message_at
    agent.touch :last_message_at
  end
end

# TODO: Is this used? Can we remove it with agent drop as well?
class MessageDrop
  def initialize(object)
    @payload = object.payload
    super
  end

  def liquid_method_missing(key)
    @payload[key]
  end

  def each(&block)
    @payload.each(&block)
  end

  def created_at
    @payload.fetch(__method__) { @object.created_at }
  end

  def as_json
    { agent: @object.agent.to_liquid.as_json, payload: @payload.as_json, created_at: created_at.as_json }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :load_agent
  before_action :load_message, except: :index

  def index
    @messages = @agent.messages
    respond_to do |format|
      format.html { render action: :index, layout: false }
    end
  end

  def show
    respond_to do |format|
      format.html { render action: :show, layout: false }
      format.json { render json: @message }
    end
  end

  def reemit
    new_message = @message.reemit!
    respond_to do |format|
      format.json { render json: new_message }
    end
  end

  def destroy
    @message.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

  def load_agent
    @agent = current_user.agents.find(params[:agent_id])
  end

  def load_message
    @message = current_user.messages.find(params[:id])
  end
end

app/views/messages/index.html.erb
<div>
  <% if @messages.empty? %>
    <p class="text-info"><em>No messages emitted.</em></p>
  <% else %>
    <table id="messages-table" class="table table-striped table-hover table-sm messages table-responsive">
      <thead>
        <tr>
          <th>Created</th>
          <th>Payload</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

      <% @messages.each do |message| %>
        <% next unless message.agent %>
        <%= content_tag :tr, class: (highlighted?(message.id) ? 'hl' : nil) do %>
          <td data-order="<%= relative_time(message.created_at, true) %>" title="<%= message.created_at %>"><%= time_ago_in_words message.created_at %> ago</td>
          <td>
            <div class="message-payload truncated message-show" data-url="<%= agent_message_path(@agent, message) %>">
                <%= truncate message.payload.to_json, :length => 200, :omission => "" %>
            </div>
          </td>
          <td>
            <div class="btn-group btn-group-sm">
              <%= link_to 'Show', '#', class: 'btn btn-primary message-show', data: { url: agent_message_path(@agent, message) }%>
              <%= link_to 'Re-emit', '#', data: { url: reemit_agent_message_path(@agent, message) }, class: 'btn btn-primary message-reemit' %>
              <%= link_to 'Delete', '#', data: { url: agent_message_path(@agent, message) }, class: "btn btn-primary message-delete" %>
            </div>
          </td>
        <% end %>
      <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/messages/show.html.erb
<p>
  <b>Created:</b> <%= (time_ago_in_words @message.created_at) %> ago
</p>
<p>
  <b>Payload:</b>
  <textarea rows="15" id="message_payload" class="form-control"><%= Utils.pretty_jsonify @message.payload || {} %></textarea>
  <div id="message_payload_editor" class="ace-editor"></div>
</p>