config/routes.rb
ActiveWorkflow::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      put :leave_workflow
      delete :remove_messages
      delete :memory, action: :destroy_memory
    end

    collection do
      get :table
      put :toggle_visibility
      get :type_details
      get :message_descriptions
      post :validate
      post :complete
      delete :undefined, action: :destroy_undefined
    end

    resources :logs, only: [:index] do
      collection do
        delete :clear
      end
    end

    resources :messages, only: [:index, :show, :destroy] do
      member do
        post :reemit
      end
    end

    scope module: :agents do
      resources :dry_runs, only: [:index, :create]
    end
  end

  scope module: :agents do
    resources :dry_runs, only: [:index, :create]
  end

  resources :workflows do
    collection do
      resource :workflow_imports, only: [:new, :create]
    end

    member do
      get :share
      get :export
      put :enable_or_disable_all_agents
      post :reset
    end

    resource :diagram, only: [:show]
  end

  resources :user_credentials, except: :show do
    collection do
      post :import
    end
  end

  resources :jobs, only: [:index, :destroy] do
    member do
      put :run
    end
    collection do
      delete :destroy_failed
      delete :destroy_all
      post :retry_queued
    end
  end

  namespace :admin do
    resources :users, except: :show do
      member do
        put :deactivate
        put :activate
        get :switch_to_user
      end
      collection do
        get :switch_back
      end
    end
  end

  get '/worker_status' => 'worker_status#show'

  match '/users/:user_id/web_requests/:agent_id/:secret' => 'web_requests#handle_request', :as => :web_requests, :via => [:get, :post, :put, :delete]

  devise_for :users,
             controllers: {
               registrations: 'users/registrations'
             },
             sign_out_via: [:post, :delete]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  mount API::V1::Root => '/api'

  get '/about' => 'home#about'
  root to: 'home#index'
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @jobs = Delayed::Job.order(Arel.sql("coalesce(failed_at,'1000-01-01'), run_at asc")).page(params[:page])

    respond_to do |format|
      format.html { render layout: !request.xhr? }
      format.json { render json: @jobs }
    end
  end

  def destroy
    @job = Delayed::Job.find(params[:id])

    respond_to do |format|
      if !running? && @job.destroy
        format.html { redirect_to jobs_path, notice: 'Job deleted.' }
        format.json { head :no_content }
      else
        format.html { redirect_to jobs_path, alert: 'Can not delete a running job.' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def run
    @job = Delayed::Job.find(params[:id])
    @job.last_error = nil

    respond_to do |format|
      if !running? && @job.update!(run_at: Time.now, failed_at: nil)
        format.html { redirect_to jobs_path, notice: 'Job enqueued.' }
        format.json { render json: @job, status: :ok }
      else
        format.html { redirect_to jobs_path, alert: 'Can not enqueue a running job.' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def retry_queued
    @jobs = Delayed::Job.awaiting_retry.update_all(run_at: Time.zone.now)

    respond_to do |format|
      format.html { redirect_to jobs_path, notice: 'Queued jobs getting retried.' }
      format.json { head :no_content }
    end
  end

  def destroy_failed
    Delayed::Job.where.not(failed_at: nil).delete_all

    respond_to do |format|
      format.html { redirect_to jobs_path, notice: 'Failed jobs removed.' }
      format.json { head :no_content }
    end
  end

  def destroy_all
    Delayed::Job.where(locked_at: nil).delete_all

    respond_to do |format|
      format.html { redirect_to jobs_path, notice: 'All jobs removed.' }
      format.json { head :no_content }
    end
  end

  private

  def running?
    (@job.locked_at || @job.locked_by) && @job.failed_at.nil?
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def status(job)
    case
    when job.failed_at
      content_tag :span, 'failed', class: 'badge badge-danger'
    when job.locked_at && job.locked_by
      content_tag :span, 'running', class: 'badge badge-info'
    else
      content_tag :span, 'queued', class: 'badge badge-warning'
    end
  end

  def relative_distance_of_time_in_words(time)
    if time < (now = Time.now)
      time_ago_in_words(time) + ' ago'
    else
      'in ' + distance_of_time_in_words(time, now)
    end
  end

  # Given an queued job, parse the stored YAML to retrieve the ID of the Agent
  # meant to be ran.
  #
  # Can return nil, or an instance of Agent.
  def agent_from_job(job)
    data = YAML.load(job.handler.to_s).try(:job_data)
    case data['job_class']
    when 'AgentCheckJob', 'AgentReceiveJob'
      Agent.find_by_id(data['arguments'][0])
    when 'AgentCleanupExpiredJob'
      'Run Message cleanup'
    else
      false
    end
  rescue ArgumentError
    # We can get to this point before all of the agents have loaded (usually,
    # in development)
    nil
  end
end

app/views/jobs/_buttons.html.erb
<div class="d-flex justify-content-end">
  <%= link_to destroy_failed_jobs_path, class: "btn btn-primary btn-sm", method: :delete do %>
    <%= icon_tag('fa-trash') %> Remove failed jobs
  <% end %>

  <%= link_to retry_queued_jobs_path, class: "btn btn-primary btn-sm", method: :post do %>
    <%= icon_tag('fa-sync-alt') %> Retry queued jobs
  <% end %>

  <%= link_to destroy_all_jobs_path, class: "btn btn-primary btn-sm", method: :delete, data: { confirm: "Are you sure you want to delete ALL pending jobs for all ActiveWorkflow users?" } do %>
    <%= icon_tag('fa-times') %> Remove all jobs
  <% end %>
</div>

app/views/jobs/index.html.erb
<% content_for :title, "Jobs" -%>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1>
          Background Jobs
        </h1>
        <% if @jobs.empty? %>
          <p class="text-info"><em>No background jobs queued.</em></p>
        <% else %>
      </div>

        <%= render 'jobs/buttons' %>
        <br/>
        <table id="jobs-table" class="table table-striped table-hover table-sm messages">
          <thead>
          <tr>
            <th>Status</th>
            <th>Agent / Job</th>
            <th>Created</th>
            <th>Next Run</th>
            <th>Attempts</th>
            <th>Last Error</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
            <% @jobs.each do |job| %>
              <tr>
                <td><%= status(job) %></td>
                <td><% case agent = agent_from_job(job)
                       when Agent
                       %><% if current_user.id == agent.user_id %><%= link_to(agent.name, agent_path(agent)) %><% else %><%= agent.name %><% end %><%
                       when String
                       %><%= agent %><%
                       when false
                       %>(system)<%
                       when nil
                       %>(deleted)<%
                       else
                       %>(unknown)<%
                       end %></td>
                <td data-order="<%= relative_time(job.created_at, true) %>" title="<%= job.created_at %>"><%= time_ago_in_words job.created_at %> ago<% if user = agent.try(:user) %> for <%= user.username %><% end %></td>
                <td data-order="<%= relative_time(job.run_at, true) %>" title="<%= job.run_at %>">
                  <% if !job.failed_at %>
                    <%= relative_distance_of_time_in_words job.run_at %>
                  <% end %>
                </td>
                <td><%= job.attempts %></td>
                <td>
                  <a data-toggle="modal" data-target="#error<%= job.id %>"><%= truncate job.last_error, :length => 90, :omission => "", :separator => "\n" %></a>
                  <div class="modal fade" id="error<%= job.id %>" tabindex="-1" role="dialog" aria-labelledby="#<%= "error#{job.id}" %>" aria-hidden="true">
                    <div class="modal-dialog big-modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h4 class="modal-title" id="myModalLabel">Error Backtrace</h4>
                          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        </div>
                        <div class="modal-body">
                          <pre>
                            <%= raw html_escape(job.last_error).split("\n").join('<br>') %>
                          </pre>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
                <td>
                  <% if (!job.locked_at && !job.locked_by) || job.failed_at.present? %>
                    <div class="btn-group btn-group-sm" style="float: right">
                      <% if (job.run_at > Time.now) || job.failed_at.present? %>
                        <%= link_to 'Run now', run_job_path(job), class: "btn btn-primary", method: :put %>
                      <% end %>
                      <%= link_to 'Delete', job_path(job), class: "btn btn-danger", method: :delete, data: { confirm: 'Really delete this job?' } %>
                    </div>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>

      <br />
      <% if @jobs.size > 10 %>
        <%= render 'jobs/buttons' %>
      <% end %>
    </div>
  </div>
</div>