config/routes.rb
ActiveWorkflow::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      put :leave_workflow
      delete :remove_messages
      delete :memory, action: :destroy_memory
    end

    collection do
      get :table
      put :toggle_visibility
      get :type_details
      get :message_descriptions
      post :validate
      post :complete
      delete :undefined, action: :destroy_undefined
    end

    resources :logs, only: [:index] do
      collection do
        delete :clear
      end
    end

    resources :messages, only: [:index, :show, :destroy] do
      member do
        post :reemit
      end
    end

    scope module: :agents do
      resources :dry_runs, only: [:index, :create]
    end
  end

  scope module: :agents do
    resources :dry_runs, only: [:index, :create]
  end

  resources :workflows do
    collection do
      resource :workflow_imports, only: [:new, :create]
    end

    member do
      get :share
      get :export
      put :enable_or_disable_all_agents
      post :reset
    end

    resource :diagram, only: [:show]
  end

  resources :user_credentials, except: :show do
    collection do
      post :import
    end
  end

  resources :jobs, only: [:index, :destroy] do
    member do
      put :run
    end
    collection do
      delete :destroy_failed
      delete :destroy_all
      post :retry_queued
    end
  end

  namespace :admin do
    resources :users, except: :show do
      member do
        put :deactivate
        put :activate
        get :switch_to_user
      end
      collection do
        get :switch_back
      end
    end
  end

  get '/worker_status' => 'worker_status#show'

  match '/users/:user_id/web_requests/:agent_id/:secret' => 'web_requests#handle_request', :as => :web_requests, :via => [:get, :post, :put, :delete]

  devise_for :users,
             controllers: {
               registrations: 'users/registrations'
             },
             sign_out_via: [:post, :delete]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  mount API::V1::Root => '/api'

  get '/about' => 'home#about'
  root to: 'home#index'
end

app/models/agents/manual_message_agent.rb
module Agents
  class ManualMessageAgent < Agent
    cannot_be_scheduled!
    cannot_receive_messages!

    description <<-MD
      Manually create messages for testing or other purposes.

      Do not set options for this agent.  Instead, connect it to other agents and create messages
      using the UI provided on this agent's Summary page.
    MD

    message_description 'User determined'

    def default_options
      { 'no options' => 'are needed' }
    end

    def handle_details_post(params)
      if params['payload']
        json = interpolate_options(JSON.parse(params['payload']))
        if json['payloads'] && (json.keys - ['payloads']).length > 0
          { success: false, error: "If you provide the 'payloads' key, please do not provide any other keys at the top level." }
        else
          [json['payloads'] || json].flatten.each do |payload|
            create_message(payload: payload)
          end
          { success: true }
        end
      else
        { success: false, error: 'You must provide a JSON payload' }
      end
    end

    def validate_options
    end
  end
end

app/views/agents/agent_views/manual_message_agent/_show.html.erb
<p>
  Use this form to manually emit messages from this agent (usually for testing).
</p>

<p>
  If you add a top-level key called <code>payloads</code> that points to an array of objects, they will be emitted as a series
  of messages. Otherwise, everything entered will be emitted as a single message.
</p>

<p>
  Liquid formatting is supported.
</p>

<h4 id="message-creation-status"></h4>

<%= form_tag handle_details_post_agent_path(@agent), :id => "create-message-form" do %>
  <div class="form-group">
    <div id="ace-payload-editor">{
}</div>
  </div>

  <%= submit_tag "Submit", :class => "btn btn-primary btn-sm" %>
<% end %>

<script>
  $(function () {
    var editor = ace.edit("ace-payload-editor")
    editor.session.setTabSize(2)
    editor.session.setUseSoftTabs(true)
    editor.session.setUseWrapMode(false)
    editor.session.setMode("ace/mode/json")
    $("#create-message-form").submit(function (e) {
      e.preventDefault();
      var $form = $("#create-message-form");
      var $status = $("#message-creation-status");
      $status.text("...");
      try{
        JSON.parse(editor.session.getValue());
      }
      catch(err){
        alert ('Sorry, there appears to be an error in your JSON input. Please fix it before continuing.');
        return false;
      }
      $.ajax({
        url: $form.attr('action'),
        method: "post",
        data: { payload: editor.session.getValue() },
        dataType: "JSON",
        success: function(json) {
          if (json.success) {
            $status.text("Success!");
          } else {
            $status.text("An error occurred: " + json.error);
          }
        },
        error: function(response) {
          $status.text("An error occurred: " + response.responseText)
        }
      });
      return false;
    });
  });
</script>